#version 450

// Writes a full screen triangle (vec4 positions) into a storage buffer that is then used as a vertex buffer.
layout(local_size_x = 3) in;

layout(set = 0, binding = 0) writeonly buffer Vertices {
    vec4 positions[];
} vertices;

void main()
{
    vec2 corners[3] = vec2[](vec2(-1.0, -1.0), vec2(3.0, -1.0), vec2(-1.0, 3.0));
    uint i = gl_LocalInvocationID.x;
    vertices.positions[i] = vec4(corners[i], 0.0, 1.0);
}
