//
// Created by Stefan Balta on 2026-09-21.
//

#ifndef PIXELKILN_IMAGEFORMAT_H
#define PIXELKILN_IMAGEFORMAT_H

enum ImageFormat {
    IMAGE_FORMAT_UNDEFINED,
    IMAGE_FORMAT_RGBA8_UNORM,
    IMAGE_FORMAT_RGBA8_SRGB,
    IMAGE_FORMAT_BGRA8_UNORM,
    IMAGE_FORMAT_BGRA8_SRGB,
    IMAGE_FORMAT_R8_UNORM,
    IMAGE_FORMAT_R32_FLOAT,
    IMAGE_FORMAT_RG32_FLOAT,
    IMAGE_FORMAT_RGBA16_FLOAT,
    IMAGE_FORMAT_RGBA32_FLOAT,
    IMAGE_FORMAT_R32_UINT,
    IMAGE_FORMAT_D16_UNORM,
    IMAGE_FORMAT_D32_FLOAT,
    IMAGE_FORMAT_COUNT
};

#endif //PIXELKILN_IMAGEFORMAT_H
