//
// Created by Stefan Balta on 2026-09-21.
//

#ifndef PIXELKILN_PRIMITIVETOPOLOGY_H
#define PIXELKILN_PRIMITIVETOPOLOGY_H

enum PrimitiveTopology {
    PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
    PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP,
    PRIMITIVE_TOPOLOGY_LINE_LIST,
    PRIMITIVE_TOPOLOGY_LINE_STRIP,
    PRIMITIVE_TOPOLOGY_POINT_LIST,
    PRIMITIVE_TOPOLOGY_COUNT
};

#endif //PIXELKILN_PRIMITIVETOPOLOGY_H
