//
// Created by Stefan Balta on 2026-08-23.
//

#ifndef PIXELKILN_UNIFORMBINDINGS_H
#define PIXELKILN_UNIFORMBINDINGS_H
#include <vector>

enum UniformBindingType {
    UNIFORM_BINDING_TYPE_BUFFER,
    UNIFORM_BINDING_TYPE_SAMPLER,
    UNIFORM_BINDING_TYPE_STORAGE_IMAGE,
    UNIFORM_BINDING_TYPE_EMPTY,
    UNIFORM_BINDING_TYPE_COUNT
};

typedef std::vector<UniformBindingType> UniformBindings;

#endif //PIXELKILN_UNIFORMBINDINGS_H
